spring:
  application:
    name: smashit

  datasource:
    url: jdbc:postgresql://localhost:5431/smashit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enable: true
    locations: classpath:db/migration

  logging:
    level:
      root: INFO
      com.totex.smashit: DEBUG
      file:
        name: logs/smashit.log